version: "3.9"
services:
  postgres-test:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres-test:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres-test
    entrypoint: [ "/app/wait-for.sh", "postgres-test:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]